<?php
namespace Jaeger\ThriftGen;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface AgentIf {
  /**
   * @param \Jaeger\ThriftGen\Span[] $spans
   */
  public function emitZipkinBatch(array $spans);
  /**
   * @param \Jaeger\ThriftGen\Batch $batch
   */
  public function emitBatch(\Jaeger\ThriftGen\Batch $batch);
}


