language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

install:
- composer install

before_script:
- vendor/bin/phpcs --standard=ZEND --standard=PSR2 --ignore=*/vendor/*,*/src/Jaeger/ThriftGen/*,*/src/Jaeger/Thrift/* ./

script:
- vendor/bin/phpunit
